# Generated by Django 2.2.4 on 2019-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190831_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
    ]
