# Generated by Django 2.2.4 on 2019-08-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_is_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_hide',
        ),
    ]
